#!/usr/bin/env python3
"""
Generate NCERT chapter JSON files for CBSE and CG Board, Class 5-10, all 5 subjects.
Output: content/chapters/{board}-{class}-{subject}.json (60 files total)
"""

import json
import os
from pathlib import Path

# ---------------------------------------------------------------------------
# Chapter data: (name_en, name_hi) per class/subject
# ---------------------------------------------------------------------------

CHAPTERS = {
    5: {
        "science": [
            ("Alive or Not Alive", "जीवित या निर्जीव"),
            ("Human Body and Health", "मानव शरीर और स्वास्थ्य"),
            ("Animals: Habitats", "जानवर: आवास"),
            ("Plants: Growing and Changing", "पौधे: वृद्धि और परिवर्तन"),
            ("Food and Nutrition", "भोजन और पोषण"),
            ("Water", "जल"),
            ("Materials and Solutions", "पदार्थ और घोल"),
            ("Force and Energy", "बल और ऊर्जा"),
            ("Our Environment", "हमारा पर्यावरण"),
            ("Weather and Seasons", "मौसम और ऋतुएँ"),
        ],
        "mathematics": [
            ("Numbers and Numeration", "संख्याएँ और संख्या-पद्धति"),
            ("Addition and Subtraction", "जोड़ और घटाव"),
            ("Multiplication and Division", "गुणा और भाग"),
            ("Fractions", "भिन्न"),
            ("Decimals", "दशमलव"),
            ("Geometry", "ज्यामिति"),
            ("Measurement", "मापन"),
            ("Data Handling", "आँकड़ों का प्रबंधन"),
            ("Patterns", "पैटर्न"),
            ("Money", "मुद्रा"),
        ],
        "hindi": [
            ("गुल्लक", "गुल्लक"),
            ("सैर-सपाटा", "सैर-सपाटा"),
            ("खिलौनेवाला", "खिलौनेवाला"),
            ("पुस्तकालय", "पुस्तकालय"),
            ("बुद्धि का फल", "बुद्धि का फल"),
            ("गुरु और चेला", "गुरु और चेला"),
            ("स्वामी की दादी", "स्वामी की दादी"),
            ("चिट्ठी पत्री", "चिट्ठी पत्री"),
            ("प्रकृति", "प्रकृति"),
            ("हमारा देश", "हमारा देश"),
        ],
        "social_science": [
            ("Our Country India", "हमारा देश भारत"),
            ("Climate of India", "भारत की जलवायु"),
            ("Maps and Globes", "मानचित्र और ग्लोब"),
            ("Resources and Development", "संसाधन और विकास"),
            ("Our Government", "हमारी सरकार"),
            ("Rights and Duties", "अधिकार और कर्तव्य"),
            ("Transport and Communication", "परिवहन और संचार"),
            ("Our Heritage", "हमारी विरासत"),
            ("The Environment", "पर्यावरण"),
            ("Safety and First Aid", "सुरक्षा और प्राथमिक उपचार"),
        ],
        "english": [
            ("Ice Cream Man", "आइसक्रीम वाला"),
            ("Wonderful Waste", "अद्भुत अपशिष्ट"),
            ("Teamwork", "टीमवर्क"),
            ("My Shadow", "मेरी परछाईं"),
            ("Robinson Crusoe", "रॉबिन्सन क्रूसो"),
            ("Who Will be Ningthou", "नींगथो कौन बनेगा"),
            ("Crystal Clear", "बिल्कुल साफ"),
            ("Nobody's Friend", "किसी का दोस्त नहीं"),
            ("Sing a Song of People", "लोगों का गाना गाओ"),
            ("Around the World", "दुनिया के चारों ओर"),
        ],
    },
    6: {
        "science": [
            ("Food: Where Does it Come From?", "भोजन: यह कहाँ से आता है?"),
            ("Components of Food", "भोजन के घटक"),
            ("Fibre to Fabric", "तंतु से वस्त्र तक"),
            ("Sorting Materials into Groups", "पदार्थों का समूहों में वर्गीकरण"),
            ("Separation of Substances", "पदार्थों का पृथक्करण"),
            ("Changes Around Us", "हमारे चारों ओर परिवर्तन"),
            ("Getting to Know Plants", "पौधों को जानिए"),
            ("Body Movements", "शरीर में गति"),
            ("The Living Organisms and Their Surroundings", "सजीव जगत और उसका परिवेश"),
            ("Motion and Measurement of Distances", "गति एवं दूरियों का मापन"),
            ("Light Shadows and Reflections", "प्रकाश छाया और परावर्तन"),
            ("Electricity and Circuits", "विद्युत तथा परिपथ"),
            ("Fun with Magnets", "चुम्बकों के साथ मज़े"),
            ("Water", "जल"),
            ("Air Around Us", "हमारे चारों ओर वायु"),
            ("Garbage In Garbage Out", "कचरा संग्रहण और निपटान"),
        ],
        "mathematics": [
            ("Knowing Our Numbers", "अपनी संख्याओं की जानकारी"),
            ("Whole Numbers", "पूर्ण संख्याएँ"),
            ("Playing with Numbers", "संख्याओं के साथ खेलना"),
            ("Basic Geometrical Ideas", "आधारभूत ज्यामितीय अवधारणाएँ"),
            ("Understanding Elementary Shapes", "प्रारंभिक आकारों को समझना"),
            ("Integers", "पूर्णांक"),
            ("Fractions", "भिन्न"),
            ("Decimals", "दशमलव"),
            ("Data Handling", "आँकड़ों का प्रबंधन"),
            ("Mensuration", "क्षेत्रमिति"),
            ("Algebra", "बीजगणित"),
            ("Ratio and Proportion", "अनुपात और समानुपात"),
            ("Symmetry", "सममिति"),
            ("Practical Geometry", "व्यावहारिक ज्यामिति"),
        ],
        "hindi": [
            ("वह चिड़िया जो", "वह चिड़िया जो"),
            ("बचपन", "बचपन"),
            ("नादान दोस्त", "नादान दोस्त"),
            ("चाँद से थोड़ी-सी गप्पें", "चाँद से थोड़ी-सी गप्पें"),
            ("अक्षरों का महत्व", "अक्षरों का महत्व"),
            ("पार नज़र के", "पार नज़र के"),
            ("साथी हाथ बढ़ाना", "साथी हाथ बढ़ाना"),
            ("झाँसी की रानी", "झाँसी की रानी"),
            ("जो देखकर भी नहीं देखते", "जो देखकर भी नहीं देखते"),
            ("संसार पुस्तक है", "संसार पुस्तक है"),
        ],
        "social_science": [
            ("What Where How and When", "क्या, कहाँ, कैसे और कब?"),
            ("On the Trail of the Earliest People", "आदिमानव की खोज में"),
            ("From Gathering to Growing Food", "संग्रह से खेती की ओर"),
            ("In the Earliest Cities", "आरंभिक नगरों में"),
            ("What Books and Burials Tell Us", "पुस्तकें और कब्रें क्या बताती हैं"),
            ("Kingdoms Kings and an Early Republic", "राज्य, राजा और एक प्राचीन गणराज्य"),
            ("New Questions and Ideas", "नए प्रश्न और विचार"),
            ("Ashoka the Emperor Who Gave Up War", "अशोक: एक अनोखा सम्राट जिसने युद्ध का त्याग किया"),
            ("The Earth in the Solar System", "सौरमंडल में पृथ्वी"),
            ("Globe Latitudes and Longitudes", "ग्लोब: अक्षांश एवं देशांतर"),
            ("Motions of the Earth", "पृथ्वी की गतियाँ"),
            ("Maps", "मानचित्र"),
        ],
        "english": [
            ("Who Did Patrick's Homework", "पैट्रिक का होमवर्क किसने किया"),
            ("How the Dog Found Himself a New Master", "कुत्ते को नया मालिक कैसे मिला"),
            ("Taro's Reward", "तारो का पुरस्कार"),
            ("An Indian American Woman in Space", "अंतरिक्ष में एक भारतीय-अमेरिकी महिला"),
            ("A Different Kind of School", "एक अलग तरह का स्कूल"),
            ("Who I Am", "मैं कौन हूँ"),
            ("Fair Play", "उचित खेल"),
            ("The Banyan Tree", "बरगद का पेड़"),
            ("Desert Animals", "रेगिस्तानी जानवर"),
            ("The Wonderful Words", "अद्भुत शब्द"),
        ],
    },
    7: {
        "science": [
            ("Nutrition in Plants", "पादपों में पोषण"),
            ("Nutrition in Animals", "प्राणियों में पोषण"),
            ("Fibre to Fabric", "ऊन और रेशम"),
            ("Heat", "ऊष्मा"),
            ("Acids Bases and Salts", "अम्ल, क्षारक और लवण"),
            ("Physical and Chemical Changes", "भौतिक एवं रासायनिक परिवर्तन"),
            ("Weather Climate and Adaptations of Animals to Climate", "मौसम, जलवायु तथा जलवायु के अनुरूप जंतुओं द्वारा अनुकूलन"),
            ("Winds Storms and Cyclones", "पवन, तूफान और चक्रवात"),
            ("Soil", "मृदा"),
            ("Respiration in Organisms", "जीवों में श्वसन"),
            ("Transportation in Animals and Plants", "जंतुओं और पादप में परिवहन"),
            ("Reproduction in Plants", "पादप में जनन"),
            ("Motion and Time", "गति एवं समय"),
            ("Electric Current and Its Effects", "विद्युत धारा और इसके प्रभाव"),
            ("Light", "प्रकाश"),
            ("Water A Precious Resource", "जल: एक बहुमूल्य संसाधन"),
            ("Forests Our Lifeline", "वन: हमारी जीवन रेखा"),
            ("Wastewater Story", "अपशिष्ट जल की कहानी"),
        ],
        "mathematics": [
            ("Integers", "पूर्णांक"),
            ("Fractions and Decimals", "भिन्न एवं दशमलव"),
            ("Data Handling", "आँकड़ों का प्रबंधन"),
            ("Simple Equations", "सरल समीकरण"),
            ("Lines and Angles", "रेखाएँ और कोण"),
            ("The Triangle and its Properties", "त्रिभुज और उसके गुण"),
            ("Congruence of Triangles", "त्रिभुजों की सर्वांगसमता"),
            ("Comparing Quantities", "राशियों की तुलना"),
            ("Rational Numbers", "परिमेय संख्याएँ"),
            ("Practical Geometry", "व्यावहारिक ज्यामिति"),
            ("Perimeter and Area", "परिमाप और क्षेत्रफल"),
            ("Algebraic Expressions", "बीजीय व्यंजक"),
            ("Exponents and Powers", "घातांक और घात"),
            ("Symmetry", "सममिति"),
            ("Visualising Solid Shapes", "ठोस आकारों का चित्रण"),
        ],
        "hindi": [
            ("हम पंछी उन्मुक्त गगन के", "हम पंछी उन्मुक्त गगन के"),
            ("दादी माँ", "दादी माँ"),
            ("हिमालय की बेटियाँ", "हिमालय की बेटियाँ"),
            ("कठपुतली", "कठपुतली"),
            ("मिठाईवाला", "मिठाईवाला"),
            ("रक्त और हमारा शरीर", "रक्त और हमारा शरीर"),
            ("पापा खो गए", "पापा खो गए"),
            ("शाम एक किसान", "शाम एक किसान"),
            ("चिड़िया की बच्ची", "चिड़िया की बच्ची"),
            ("अपूर्व अनुभव", "अपूर्व अनुभव"),
        ],
        "social_science": [
            ("Tracing Changes Through a Thousand Years", "हजार वर्षों के दौरान हुए परिवर्तनों की पड़ताल"),
            ("New Kings and Kingdoms", "नए राजा और राज्य"),
            ("The Delhi Sultans", "दिल्ली के सुलतान"),
            ("The Mughal Empire", "मुगल साम्राज्य"),
            ("Rulers and Buildings", "शासक और इमारतें"),
            ("Towns Traders and Craftspeople", "नगर, व्यापारी और शिल्पी"),
            ("Tribes Nomads and Settled Communities", "जनजातियाँ, खानाबदोश और एक जगह बसे हुए समुदाय"),
            ("Devotional Paths to the Divine", "ईश्वर से अनुराग"),
            ("Environment", "पर्यावरण"),
            ("Inside Our Earth", "हमारी पृथ्वी के भीतर"),
            ("Our Changing Earth", "हमारी बदलती पृथ्वी"),
            ("Air", "वायु"),
        ],
        "english": [
            ("Three Questions", "तीन प्रश्न"),
            ("A Gift of Chappals", "चप्पलों का उपहार"),
            ("Gopal and the Hilsa Fish", "गोपाल और हिल्सा मछली"),
            ("The Ashes That Made Trees Bloom", "राख जिसने पेड़ों को खिलाया"),
            ("Quality", "गुणवत्ता"),
            ("Expert Detectives", "विशेषज्ञ जासूस"),
            ("The Invention of Vita-Wonk", "विटा-वॉन्क का आविष्कार"),
            ("Fire Friend and Foe", "अग्नि: मित्र और शत्रु"),
            ("A Bicycle in Good Repair", "अच्छी हालत में साइकिल"),
            ("The Story of Cricket", "क्रिकेट की कहानी"),
        ],
    },
    8: {
        "science": [
            ("Crop Production and Management", "फसल उत्पादन और प्रबंध"),
            ("Microorganisms Friend and Foe", "सूक्ष्मजीव: मित्र एवं शत्रु"),
            ("Synthetic Fibres and Plastics", "संश्लेषित रेशे और प्लास्टिक"),
            ("Materials Metals and Non-Metals", "पदार्थ: धातु एवं अधातु"),
            ("Coal and Petroleum", "कोयला और पेट्रोलियम"),
            ("Combustion and Flame", "दहन और ज्वाला"),
            ("Conservation of Plants and Animals", "पौधे और जंतुओं का संरक्षण"),
            ("Cell Structure and Functions", "कोशिका: संरचना एवं प्रकार्य"),
            ("Reproduction in Animals", "जंतुओं में जनन"),
            ("Reaching the Age of Adolescence", "किशोरावस्था की ओर"),
            ("Force and Pressure", "बल तथा दाब"),
            ("Friction", "घर्षण"),
            ("Sound", "ध्वनि"),
            ("Chemical Effects of Electric Current", "विद्युत धारा के रासायनिक प्रभाव"),
            ("Some Natural Phenomena", "कुछ प्राकृतिक परिघटनाएँ"),
            ("Light", "प्रकाश"),
            ("Stars and the Solar System", "तारे एवं सौर परिवार"),
            ("Pollution of Air and Water", "वायु तथा जल का प्रदूषण"),
        ],
        "mathematics": [
            ("Rational Numbers", "परिमेय संख्याएँ"),
            ("Linear Equations in One Variable", "एक चर वाले रैखिक समीकरण"),
            ("Understanding Quadrilaterals", "चतुर्भुजों को समझना"),
            ("Practical Geometry", "व्यावहारिक ज्यामिति"),
            ("Data Handling", "आँकड़ों का प्रबंधन"),
            ("Squares and Square Roots", "वर्ग और वर्गमूल"),
            ("Cubes and Cube Roots", "घन और घनमूल"),
            ("Comparing Quantities", "राशियों की तुलना"),
            ("Algebraic Expressions and Identities", "बीजीय व्यंजक एवं सर्वसमिकाएँ"),
            ("Visualising Solid Shapes", "ठोस आकारों का चित्रण"),
            ("Mensuration", "क्षेत्रमिति"),
            ("Exponents and Powers", "घातांक और घात"),
            ("Direct and Inverse Proportions", "सीधा और व्युत्क्रम समानुपात"),
            ("Factorisation", "गुणनखंडन"),
            ("Introduction to Graphs", "आलेखों से परिचय"),
            ("Playing with Numbers", "संख्याओं के साथ खेलना"),
        ],
        "hindi": [
            ("ध्वनि", "ध्वनि"),
            ("लाख की चूड़ियाँ", "लाख की चूड़ियाँ"),
            ("बस की यात्रा", "बस की यात्रा"),
            ("दीवानों की हस्ती", "दीवानों की हस्ती"),
            ("चिट्ठियों की अनूठी दुनिया", "चिट्ठियों की अनूठी दुनिया"),
            ("भगवान के डाकिये", "भगवान के डाकिये"),
            ("क्या निराश हुआ जाए", "क्या निराश हुआ जाए"),
            ("यह सबसे कठिन समय नहीं", "यह सबसे कठिन समय नहीं"),
            ("कबीर की सखियाँ", "कबीर की सखियाँ"),
            ("कामचोर", "कामचोर"),
        ],
        "social_science": [
            ("How When and Where", "कैसे, कब और कहाँ"),
            ("From Trade to Territory", "व्यापार से साम्राज्य तक"),
            ("Ruling the Countryside", "ग्रामीण क्षेत्र पर शासन"),
            ("Tribals Dikus and the Vision of a Golden Age", "आदिवासी दिकू और एक स्वर्ण युग की कल्पना"),
            ("When People Rebel", "जब जनता बगावत करती है"),
            ("Weavers Iron Smelters and Factory Owners", "बुनकर लौह-स्मेल्टर और फैक्ट्री मालिक"),
            ("Civilising the Native Educating the Nation", "देशी जनता को सभ्य बनाना: राष्ट्र को शिक्षित करना"),
            ("Women Caste and Reform", "महिलाएँ जाति और सुधार"),
            ("Resources", "संसाधन"),
            ("Land Soil Water Natural Vegetation and Wildlife", "भूमि, मृदा, जल, प्राकृतिक वनस्पति और वन्य जीवन"),
            ("Agriculture", "कृषि"),
            ("Industries", "उद्योग"),
        ],
        "english": [
            ("The Best Christmas Present in the World", "विश्व का सर्वश्रेष्ठ क्रिसमस उपहार"),
            ("The Tsunami", "सुनामी"),
            ("Glimpses of the Past", "अतीत की झलकियाँ"),
            ("Bepin Choudhry's Lapse of Memory", "बेपिन चौधरी की स्मृतिलोप"),
            ("The Summit Within", "भीतर का शिखर"),
            ("This is Jody's Fawn", "यह जोडी का हिरण-शावक है"),
            ("A Visit to Cambridge", "कैम्ब्रिज की यात्रा"),
            ("A Short Monsoon Diary", "एक संक्षिप्त मानसून डायरी"),
            ("The Great Stone Face", "महान पत्थर का चेहरा"),
            ("Jalebis", "जलेबियाँ"),
        ],
    },
    9: {
        "science": [
            ("Matter in Our Surroundings", "हमारे आस-पास के पदार्थ"),
            ("Is Matter Around Us Pure", "क्या हमारे आस-पास के पदार्थ शुद्ध हैं"),
            ("Atoms and Molecules", "परमाणु एवं अणु"),
            ("Structure of the Atom", "परमाणु की संरचना"),
            ("The Fundamental Unit of Life", "जीवन की मौलिक इकाई"),
            ("Tissues", "ऊतक"),
            ("Diversity in Living Organisms", "जीवों में विविधता"),
            ("Motion", "गति"),
            ("Force and Laws of Motion", "बल तथा गति के नियम"),
            ("Gravitation", "गुरुत्वाकर्षण"),
            ("Work and Energy", "कार्य और ऊर्जा"),
            ("Sound", "ध्वनि"),
            ("Why Do We Fall Ill", "हम बीमार क्यों होते हैं"),
            ("Natural Resources", "प्राकृतिक संपदा"),
            ("Improvement in Food Resources", "खाद्य संसाधनों में सुधार"),
        ],
        "mathematics": [
            ("Number Systems", "संख्या पद्धति"),
            ("Polynomials", "बहुपद"),
            ("Coordinate Geometry", "निर्देशांक ज्यामिति"),
            ("Linear Equations in Two Variables", "दो चरों वाले रैखिक समीकरण"),
            ("Introduction to Euclid's Geometry", "यूक्लिड की ज्यामिति का परिचय"),
            ("Lines and Angles", "रेखाएँ और कोण"),
            ("Triangles", "त्रिभुज"),
            ("Quadrilaterals", "चतुर्भुज"),
            ("Areas of Parallelograms and Triangles", "समान्तर चतुर्भुजों और त्रिभुजों के क्षेत्रफल"),
            ("Circles", "वृत्त"),
            ("Constructions", "रचनाएँ"),
            ("Heron's Formula", "हीरोन का सूत्र"),
            ("Surface Areas and Volumes", "पृष्ठीय क्षेत्रफल और आयतन"),
            ("Statistics", "सांख्यिकी"),
            ("Probability", "प्रायिकता"),
        ],
        "hindi": [
            ("दो बैलों की कथा", "दो बैलों की कथा"),
            ("ल्हासा की ओर", "ल्हासा की ओर"),
            ("उपभोक्तावाद की संस्कृति", "उपभोक्तावाद की संस्कृति"),
            ("साँवले सपनों की याद", "साँवले सपनों की याद"),
            ("नाना साहब की पुत्री देवी मैना को भस्म कर दिया गया", "नाना साहब की पुत्री देवी मैना को भस्म कर दिया गया"),
            ("प्रेमचंद के फटे जूते", "प्रेमचंद के फटे जूते"),
            ("मेरे बचपन के दिन", "मेरे बचपन के दिन"),
            ("एक कुत्ता और एक मैना", "एक कुत्ता और एक मैना"),
            ("साखियाँ एवं सबद", "साखियाँ एवं सबद"),
            ("वाख", "वाख"),
        ],
        "social_science": [
            ("The French Revolution", "फ्रांसीसी क्रांति"),
            ("Socialism in Europe and the Russian Revolution", "यूरोप में समाजवाद और रूसी क्रांति"),
            ("Nazism and the Rise of Hitler", "नात्सीवाद और हिटलर का उदय"),
            ("Forest Society and Colonialism", "वन समाज और उपनिवेशवाद"),
            ("Pastoralists in the Modern World", "आधुनिक विश्व में चरवाहे"),
            ("India Size and Location", "भारत: आकार और स्थिति"),
            ("Physical Features of India", "भारत का भौतिक स्वरूप"),
            ("Drainage", "अपवाह"),
            ("Climate", "जलवायु"),
            ("Natural Vegetation and Wild Life", "प्राकृतिक वनस्पति तथा वन्य प्राणी"),
            ("Democracy in the Contemporary World", "समकालीन विश्व में लोकतंत्र"),
            ("What is Democracy Why Democracy", "लोकतंत्र क्या है? लोकतंत्र क्यों?"),
        ],
        "english": [
            ("The Fun They Had", "उनका मज़ा"),
            ("The Sound of Music", "संगीत की ध्वनि"),
            ("The Little Girl", "छोटी लड़की"),
            ("A Truly Beautiful Mind", "सच में सुंदर मन"),
            ("The Snake and the Mirror", "साँप और दर्पण"),
            ("My Childhood", "मेरा बचपन"),
            ("Packing", "पैकिंग"),
            ("Reach for the Top", "शीर्ष पर पहुँचो"),
            ("The Bond of Love", "प्रेम का बंधन"),
            ("Kathmandu", "काठमांडू"),
        ],
    },
    10: {
        "science": [
            ("Chemical Reactions and Equations", "रासायनिक अभिक्रियाएँ एवं समीकरण"),
            ("Acids Bases and Salts", "अम्ल, क्षारक एवं लवण"),
            ("Metals and Non-metals", "धातु एवं अधातु"),
            ("Carbon and its Compounds", "कार्बन एवं उसके यौगिक"),
            ("Life Processes", "जैव प्रक्रम"),
            ("Control and Coordination", "नियंत्रण एवं समन्वय"),
            ("How do Organisms Reproduce", "जीव जनन कैसे करते हैं"),
            ("Heredity", "अनुवांशिकता"),
            ("Light Reflection and Refraction", "प्रकाश: परावर्तन तथा अपवर्तन"),
            ("The Human Eye and the Colourful World", "मानव नेत्र तथा रंगबिरंगा संसार"),
            ("Electricity", "विद्युत"),
            ("Magnetic Effects of Electric Current", "विद्युत धारा के चुम्बकीय प्रभाव"),
            ("Our Environment", "हमारा पर्यावरण"),
        ],
        "mathematics": [
            ("Real Numbers", "वास्तविक संख्याएँ"),
            ("Polynomials", "बहुपद"),
            ("Pair of Linear Equations in Two Variables", "दो चरों वाले रैखिक समीकरणों का युग्म"),
            ("Quadratic Equations", "द्विघात समीकरण"),
            ("Arithmetic Progressions", "समांतर श्रेढ़ियाँ"),
            ("Triangles", "त्रिभुज"),
            ("Coordinate Geometry", "निर्देशांक ज्यामिति"),
            ("Introduction to Trigonometry", "त्रिकोणमिति का परिचय"),
            ("Some Applications of Trigonometry", "त्रिकोणमिति के कुछ अनुप्रयोग"),
            ("Circles", "वृत्त"),
            ("Areas Related to Circles", "वृत्तों से संबंधित क्षेत्रफल"),
            ("Surface Areas and Volumes", "पृष्ठीय क्षेत्रफल और आयतन"),
            ("Statistics", "सांख्यिकी"),
            ("Probability", "प्रायिकता"),
        ],
        "hindi": [
            ("साखी", "साखी"),
            ("पद", "पद"),
            ("दोहे", "दोहे"),
            ("मानवीय करुणा की दिव्य चमक", "मानवीय करुणा की दिव्य चमक"),
            ("बालगोबिन भगत", "बालगोबिन भगत"),
            ("नेताजी का चश्मा", "नेताजी का चश्मा"),
            ("एक कहानी यह भी", "एक कहानी यह भी"),
            ("नौबतखाने में इबादत", "नौबतखाने में इबादत"),
            ("संस्कृति", "संस्कृति"),
            ("लखनवी अंदाज़", "लखनवी अंदाज़"),
        ],
        "social_science": [
            ("The Rise of Nationalism in Europe", "यूरोप में राष्ट्रवाद का उदय"),
            ("Nationalism in India", "भारत में राष्ट्रवाद"),
            ("The Making of a Global World", "भूमंडलीकृत विश्व का बनना"),
            ("The Age of Industrialisation", "औद्योगीकरण का युग"),
            ("Print Culture and the Modern World", "मुद्रण संस्कृति और आधुनिक दुनिया"),
            ("Resources and Development", "संसाधन और विकास"),
            ("Forest and Wildlife Resources", "वन और वन्य जीव संसाधन"),
            ("Water Resources", "जल संसाधन"),
            ("Agriculture", "कृषि"),
            ("Minerals and Energy Resources", "खनिज और ऊर्जा संसाधन"),
            ("Power Sharing", "सत्ता की साझेदारी"),
            ("Federalism", "संघवाद"),
        ],
        "english": [
            ("A Letter to God", "भगवान को पत्र"),
            ("Nelson Mandela Long Walk to Freedom", "नेल्सन मंडेला: स्वतंत्रता की लंबी राह"),
            ("Two Stories about Flying", "उड़ान की दो कहानियाँ"),
            ("From the Diary of Anne Frank", "ऐनी फ्रैंक की डायरी से"),
            ("The Hundred Dresses", "सौ पोशाकें"),
            ("A Baker from Goa", "गोआ का एक नानबाई"),
            ("Coorg", "कूर्ग"),
            ("Tea from Assam", "असम की चाय"),
            ("The Trees", "वृक्ष"),
            ("Fog", "कोहरा"),
        ],
    },
}

BOARDS = ["cbse", "cg"]
SUBJECTS = ["science", "mathematics", "hindi", "social_science", "english"]
CLASSES = [5, 6, 7, 8, 9, 10]

OUTPUT_DIR = Path(__file__).parent.parent / "content" / "chapters"


def generate_file(board: str, cls: int, subject: str) -> None:
    chapters_raw = CHAPTERS[cls][subject]
    chapters = []
    for i, (name_en, name_hi) in enumerate(chapters_raw, start=1):
        chapters.append({
            "number": i,
            "name_hi": name_hi,
            "name_en": name_en,
            "is_hero": i <= 2,
        })

    data = {
        "board": board,
        "class": cls,
        "subject": subject,
        "total_chapters": len(chapters),
        "chapters": chapters,
    }

    filename = f"{board}-{cls}-{subject}.json"
    out_path = OUTPUT_DIR / filename
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  wrote {filename}  ({len(chapters)} chapters)")


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for board in BOARDS:
        for cls in CLASSES:
            for subject in SUBJECTS:
                generate_file(board, cls, subject)
                count += 1
    print(f"\nDone. Generated {count} files in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
